//! Golden file regression tests.
//!
//! Each fixture has a golden expected output generated by decruft itself.
//! Tests compare current extraction against the golden file exactly
//! (after whitespace normalization). Any difference indicates a
//! behavioral change that should be reviewed.
//!
//! To regenerate golden files after intentional changes:
//!   cargo test --test golden -- --ignored regenerate
//!
//! This is the primary regression test. The oracle tests (Jaccard
//! similarity against defuddle) serve as competitive benchmarking only.

#![allow(clippy::panic)]

use decruft::{DecruftOptions, parse};
use std::fs;
use std::path::PathBuf;

fn golden_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/expected/golden")
}

/// Normalize whitespace for comparison: collapse runs, trim lines.
fn normalize(s: &str) -> String {
    s.lines()
        .map(|line| line.split_whitespace().collect::<Vec<_>>().join(" "))
        .collect::<Vec<_>>()
        .join("\n")
}

// ── Defuddle fixtures ────────────────────────────────────────────

#[test]
fn golden_defuddle_fixtures() {
    let fixture_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/defuddle");
    let golden = golden_dir().join("defuddle");

    let mut failures = Vec::new();
    let mut total = 0;

    for entry in fs::read_dir(&fixture_dir).unwrap().flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("html") {
            continue;
        }
        let name = path.file_stem().unwrap().to_string_lossy().to_string();
        let golden_path = golden.join(format!("{name}.html"));

        let Ok(expected) = fs::read_to_string(&golden_path) else {
            continue;
        };

        total += 1;
        let html = fs::read_to_string(&path).unwrap();
        let result = parse(&html, &DecruftOptions::default());

        if normalize(&result.content) != normalize(&expected) {
            failures.push(name);
        }
    }

    assert!(total >= 100, "expected ≥100 golden files, got {total}");
    assert!(
        failures.is_empty(),
        "Golden file mismatches ({}/{total}):\n  {}",
        failures.len(),
        failures.join("\n  ")
    );
}

// ── Mozilla fixtures ─────────────────────────────────────────────

#[test]
fn golden_mozilla_fixtures() {
    let fixture_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/mozilla");
    let golden = golden_dir().join("mozilla");

    let mut failures = Vec::new();
    let mut total = 0;

    for entry in fs::read_dir(&fixture_dir).unwrap().flatten() {
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let name = path.file_name().unwrap().to_string_lossy().to_string();
        let source = path.join("source.html");
        let golden_path = golden.join(format!("{name}.html"));

        let Ok(expected) = fs::read_to_string(&golden_path) else {
            continue;
        };
        let Ok(html) = fs::read_to_string(&source) else {
            continue;
        };

        total += 1;
        let result = parse(&html, &DecruftOptions::default());

        if normalize(&result.content) != normalize(&expected) {
            failures.push(name);
        }
    }

    assert!(total >= 100, "expected ≥100 golden files, got {total}");
    assert!(
        failures.is_empty(),
        "Golden file mismatches ({}/{total}):\n  {}",
        failures.len(),
        failures.join("\n  ")
    );
}

// ── Regeneration (run with --ignored) ────────────────────────────

#[test]
#[ignore = "run manually to regenerate golden files"]
fn regenerate_golden_files() {
    let fixture_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/defuddle");
    let golden = golden_dir().join("defuddle");
    fs::create_dir_all(&golden).unwrap();

    let mut count = 0;
    for entry in fs::read_dir(&fixture_dir).unwrap().flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("html") {
            continue;
        }
        let name = path.file_stem().unwrap().to_string_lossy().to_string();
        let html = fs::read_to_string(&path).unwrap();
        let result = parse(&html, &DecruftOptions::default());
        fs::write(golden.join(format!("{name}.html")), &result.content).unwrap();
        count += 1;
    }

    let mozilla_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/mozilla");
    let mozilla_golden = golden_dir().join("mozilla");
    fs::create_dir_all(&mozilla_golden).unwrap();

    for entry in fs::read_dir(&mozilla_dir).unwrap().flatten() {
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let name = path.file_name().unwrap().to_string_lossy().to_string();
        let source = path.join("source.html");
        let Ok(html) = fs::read_to_string(&source) else {
            continue;
        };
        let result = parse(&html, &DecruftOptions::default());
        fs::write(mozilla_golden.join(format!("{name}.html")), &result.content).unwrap();
        count += 1;
    }

    panic!(
        "Regenerated {count} golden files. Review changes with: git diff tests/expected/golden/"
    );
}
