//! Golden file regression tests — the primary gate.
//!
//! Each fixture has a golden expected output generated by decruft.
//! Tests compare current extraction against the golden file exactly
//! (after whitespace normalization). Any difference means extraction
//! behavior changed and must be reviewed.
//!
//! To regenerate after intentional changes:
//!
//!     cargo test --test regression -- --ignored regenerate
//!
//! Then review with `git diff tests/expected/golden/`.

#![allow(clippy::panic)]

use decruft::{DecruftOptions, parse};
use std::fs;
use std::path::PathBuf;

fn golden_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/expected/golden")
}

fn normalize(s: &str) -> String {
    s.lines()
        .map(|line| line.split_whitespace().collect::<Vec<_>>().join(" "))
        .collect::<Vec<_>>()
        .join("\n")
}

// ── Defuddle fixtures (144) ─────────────────────────────────────

#[test]
fn defuddle_golden() {
    let fixture_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/defuddle");
    let golden = golden_dir().join("defuddle");

    let mut failures = Vec::new();
    let mut total = 0;

    for entry in fs::read_dir(&fixture_dir).unwrap().flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("html") {
            continue;
        }
        let name = path.file_stem().unwrap().to_string_lossy().to_string();
        let golden_path = golden.join(format!("{name}.html"));

        let Ok(expected) = fs::read_to_string(&golden_path) else {
            continue;
        };

        total += 1;
        let html = fs::read_to_string(&path).unwrap();
        let result = parse(&html, &DecruftOptions::default());

        if normalize(&result.content) != normalize(&expected) {
            failures.push(name);
        }
    }

    assert!(total >= 100, "expected ≥100 golden files, got {total}");
    assert!(
        failures.is_empty(),
        "{}/{total} golden mismatches:\n  {}\n\n\
         Regenerate with: cargo test --test regression -- --ignored regenerate",
        failures.len(),
        failures.join("\n  ")
    );
}

// ── Mozilla fixtures (130) ──────────────────────────────────────

#[test]
fn mozilla_golden() {
    let fixture_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/mozilla");
    let golden = golden_dir().join("mozilla");

    let mut failures = Vec::new();
    let mut total = 0;

    for entry in fs::read_dir(&fixture_dir).unwrap().flatten() {
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let name = path.file_name().unwrap().to_string_lossy().to_string();
        let source = path.join("source.html");
        let golden_path = golden.join(format!("{name}.html"));

        let Ok(expected) = fs::read_to_string(&golden_path) else {
            continue;
        };
        let Ok(html) = fs::read_to_string(&source) else {
            continue;
        };

        total += 1;
        let result = parse(&html, &DecruftOptions::default());

        if normalize(&result.content) != normalize(&expected) {
            failures.push(name);
        }
    }

    assert!(total >= 100, "expected ≥100 golden files, got {total}");
    assert!(
        failures.is_empty(),
        "{}/{total} golden mismatches:\n  {}\n\n\
         Regenerate with: cargo test --test regression -- --ignored regenerate",
        failures.len(),
        failures.join("\n  ")
    );
}

// ── Regeneration ────────────────────────────────────────────────

#[test]
#[ignore = "run manually to regenerate golden files"]
fn regenerate() {
    let mut count = 0;

    // Defuddle
    let defuddle_fixtures =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/defuddle");
    let defuddle_golden = golden_dir().join("defuddle");
    fs::create_dir_all(&defuddle_golden).unwrap();

    for entry in fs::read_dir(&defuddle_fixtures).unwrap().flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("html") {
            continue;
        }
        let name = path.file_stem().unwrap().to_string_lossy().to_string();
        let html = fs::read_to_string(&path).unwrap();
        let result = parse(&html, &DecruftOptions::default());
        fs::write(
            defuddle_golden.join(format!("{name}.html")),
            &result.content,
        )
        .unwrap();
        count += 1;
    }

    // Mozilla
    let mozilla_fixtures = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/mozilla");
    let mozilla_golden = golden_dir().join("mozilla");
    fs::create_dir_all(&mozilla_golden).unwrap();

    for entry in fs::read_dir(&mozilla_fixtures).unwrap().flatten() {
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let name = path.file_name().unwrap().to_string_lossy().to_string();
        let source = path.join("source.html");
        let Ok(html) = fs::read_to_string(&source) else {
            continue;
        };
        let result = parse(&html, &DecruftOptions::default());
        fs::write(mozilla_golden.join(format!("{name}.html")), &result.content).unwrap();
        count += 1;
    }

    panic!("Regenerated {count} golden files. Review with: git diff tests/expected/golden/");
}
