name: Docs

on:
  push:
    branches: [main]

permissions:
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  docs:
    name: Build and deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - run: cargo doc --no-deps
        env:
          RUSTDOCFLAGS: "--cfg docsrs"

      - name: Add redirect index
        run: echo '<meta http-equiv="refresh" content="0;url=decruft/index.html">' > target/doc/index.html

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc

      - id: deploy
        uses: actions/deploy-pages@v4
